version: '3.7'
# Other docker-compose examples in /examples

services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    #volumes:
    #  - "mc:/data"
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: 1.20.1
      MODS_FILE: /extras/mods.txt
      REMOVE_OLD_MODS: "true"
    restart: unless-stopped
    volumes:
      - /mnt/docker_zvol/mc/data:/data
      - /mnt/docker_zvol/mc/mods.txt:/extras/mods.txt:ro
    cpus: "2"
    mem_limit: "2g"
    mem_reservation: "1g"
    deploy:
        resources:
            limits:
              cpus: "3"

#volumes:
#  mc: {}
